### ISSUE TITLE
Remove extra margin-top in the table of content of the page

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonita-documentation-theme#123]
This has been introduced and detected https://github.com/bonitasoft/bonita-documentation-theme/pull/86#pullrequestreview-936094216 (follow this link to see screenshots showing the margin increase) to make the TOC fully visible when a banner is displayed. The margin is always set whereas it is not needed when there is no banner.

**Tip for banner detection**
The banner is displayed when an AsciiDoc page attribute is set. There are several attributes that are available. Each of them displays a different type of banner.
We could introduce an handlebars helper function that will detect when the banner is present (i.e if one of the AsciiDoc page attribute is set) and in this case, add a CSS class to add the margin top

**Comment by akantcheff** [comment]
Hello! I can take a look on this one :)

**Comment by tbouffard** [comment]
First attempt done in #179.
Not accepted, see https://github.com/bonitasoft/bonita-documentation-theme/pull/179#pullrequestreview-1313398994

It's not currently a priority, but it's still something we want to address. So let's keep it open and deal with it later.
