### ISSUE TITLE
Provide a way to avoid duplicating "Bonita editions" admonitions in all Enterprise edition pages

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonita-documentation-theme#129]
Today, the wording is duplicated in all pages. This makes hard to modify the message and strange for external contributors.

See discussions that occurred in https://github.com/bonitasoft/bonita-doc/pull/1534. Someone wanted to update the messaging because he said _Text updates to reflect only Enterprise edition as of 2021.1_. Please read all comments of the PR to get the whole context.

If we decide to implement a solution, we should choose carefully the version of the document where we apply the change.

There are mentions to the Enterprise edition in Bonita 7.7

https://documentation.bonitasoft.com/bonita/7.7/cluster-administration
![image](https://user-images.githubusercontent.com/27200110/145222448-d985f3d9-b1dc-4bd7-87a0-fbb4bb08daf3.png)

### Messages of the edition notices in pages today

**All editions**

This is the most common notice we have: `In Teamwork, Efficiency, Performance and Enterprise editions` (sometimes not in this order like in https://github.com/bonitasoft/bonita-doc/blob/048664655e8c6bb5b2a128e93680d4e282fe69f4/modules/best-practices/pages/project-documentation-generation.adoc 😢)

https://github.com/bonitasoft/bonita-doc/pull/1881#pullrequestreview-852807600 describes the recent usage of `For Subscription editions only.`

**Performance and Efficiency**

https://documentation.bonitasoft.com/bonita/2021.2/identity/bdm-access-control

[<img src="https://user-images.githubusercontent.com/27200110/145221924-a93e5332-c805-455b-bd28-aeaad5fcf2d6.png" width="400"/>](https://user-images.githubusercontent.com/27200110/145221924-a93e5332-c805-455b-bd28-aeaad5fcf2d6.png)

**Performance only**

https://github.com/bonitasoft/bonita-doc/blob/530204702d936448c9eebba61dab73615bbadf33/modules/runtime/pages/overview-of-bonita-bpm-in-a-cluster.adoc
https://documentation.bonitasoft.com/bonita/2021.2/runtime/overview-of-bonita-bpm-in-a-cluster

[<img src="https://user-images.githubusercontent.com/27200110/145221345-a49fa63c-205f-44b2-ae23-80534d640b12.png" width="400"/>](https://user-images.githubusercontent.com/27200110/145221345-a49fa63c-205f-44b2-ae23-80534d640b12.png)

### Position of the edition notices in pages today

It is generally on top of the page or just under the 1st paragraph

### Special cases today

**After paragraphs and warnings + custom message**

https://documentation.bonitasoft.com/bonita/7.10/purge-tool
https://github.com/bonitasoft/bonita-doc/blob/9d4f0689908ba9ac5962b2deaeed83f89729c5ce/modules/ROOT/pages/purge-tool.adoc

[<img src="https://user-images.githubusercontent.com/27200110/145223199-272f8c1b-6a92-47de-97f3-a660565bc9c2.png" width="400"/>](https://user-images.githubusercontent.com/27200110/145223199-272f8c1b-6a92-47de-97f3-a660565bc9c2.png)

**important**: it contains a custom message in addition to the editions notice

**In paragraph titles**
in this case, a regular admonition notice will be more convenient

https://documentation.bonitasoft.com/bonita/2021.2/api/form-api#_update_a_form_mapping_efficiency_performance_and_enterprise_editions

[<img src="https://user-images.githubusercontent.com/27200110/145224381-a42ba457-22f6-46ad-aebb-2f876ee2204f.png" width="400"/>](https://user-images.githubusercontent.com/27200110/145224381-a42ba457-22f6-46ad-aebb-2f876ee2204f.png)

**In several paragraph of the same page**

https://documentation.bonitasoft.com/bonita/2021.2/software-extensibility/software-extensibility
https://github.com/bonitasoft/bonita-doc/blob/048664655e8c6bb5b2a128e93680d4e282fe69f4/modules/software-extensibility/pages/software-extensibility.adoc

![image](https://user-images.githubusercontent.com/27200110/150174270-5eb38710-c917-4fdb-9fd3-b82a1637646c.png)

**Others**

See proposed changes in the multi-tenancy page
- https://github.com/bonitasoft/bonita-doc/pull/1846 
- https://github.com/bonitasoft/bonita-doc/pull/1848 

### Proposals

Feel free to update the description or add comments with more suggestions or agree/disagree with proposals

**Proposal 1: Define an AsciiDoc attribute in the page and in the theme, generate the admonition accordingly**

For instance: `bonita-edition: <>` / default: community (no admonition)

- if `Enterprise`, put  `Enterprise`
- otherwise, the minimal subscription edition must be set, for instance `Efficiency`

cons
- need doc for the enumeration values
- not flexible for positioning. Not possible except by setting more attributes to manage position on top, after the 1st paragraph or in the middle of the page

**Proposal 2: use custom Asciidoc syntax**

Provide a custom AsciiDoc block/syntax that can be put everywhere and the thee interprets it to generated the admonition.
For instance {BonitaLicense=efficiency}

pros
- options to select the edition
- can be placed everywhere

cons
- custom
- need a theme update

**Proposal 3: use Antora partials**

https://docs.antora.org/antora/2.3/partials-directory/
https://docs.antora.org/antora/2.3/page/partials-and-content-snippets/

pros
- define the partial directly in the repository content
- can create a partial file for each use case
- use it as include, so it can be easily placed everywhere
- no dependency on theme, so can be started immediately
- we can have different content per version i.e. we are able to change the messaging depending of the Bonita version

cons
- duplication in versions/branches

**Comment by vbotnari12** [comment]
Can I know why are you handling this battle on your own? :) For your information, if I was not curious and meddling everywhere, I would NOT have been aware of the decision taken regarding edition admonitions. We sure need to find a way to share this kind of information...

**Comment by tbouffard** [comment]
https://github.com/bonitasoft/bonita-documentation-site/pull/449 includes guidance in the `Contributing Guide`.
Work has to be done in the `bonita-doc` repository. See https://github.com/bonitasoft/bonita-doc/pull/2182

So closing.
