### ISSUE TITLE
Make the Contributing Guide more visible

### ISSUE THREAD

**Issue by jeromecambon** [bonitasoft/bonita-documentation-theme#145]
Currently, the [Contribution Guide](https://github.com/bonitasoft/bonita-documentation-site/blob/master/docs/content/CONTRIBUTING.adoc) is not well visible to the doc contributors. and is often not read.

The idea is to make it visible close to the "Edit this page" button, so that the contributors can obviously see (and read!) it.
Here is the proposed design:
<img width="805" alt="Screen Shot 2022-10-07 at 1 53 32 PM" src="https://user-images.githubusercontent.com/17833345/194588121-2cdd378d-c329-4917-a808-fbc537f95e41.png">

The first (pencil) icon will have a "Edit this page" tooltip, and point (as before) on the github editor.
The second icon (info) will have a "How to contribute" tooltip and point on the [Contribution Guide](https://github.com/bonitasoft/bonita-documentation-site/blob/master/docs/content/CONTRIBUTING.adoc).

The design will also adapt to the light and dark themes.

As a reminder, here is the current "Edit button" look and feel

![image](https://user-images.githubusercontent.com/27200110/195766016-b3aa1ba6-d8f7-423d-b2dc-6e8040b6fbbd.png)

**Comment by tbouffard** [comment]
Sources of inspiration: https://docs.fedoraproject.org/en-US/fedora/f30/ 

![image](https://user-images.githubusercontent.com/27200110/195764882-96c010fb-83a2-41be-a0ef-85db069c4aa4.png)

**Comment by tbouffard** [comment]
@jeromecambon we could also add a button as in the fedora docs to link to the git history of the source file. This will be a first iteration for https://github.com/bonitasoft/bonita-documentation-site/issues/435

**Comment by tbouffard** [comment]
> an URL for the history.

the toolbar.hbs is using `edit2var` to transform the `edit.url`and generate the url to the commits history of the file
see https://gitlab.com/fedora/docs/docs-website/ui-bundle/-/blob/main/src/helpers/edit2var.js
