### ISSUE TITLE
A page should have the Edit icon when half of a screen

### ISSUE THREAD

**Issue by jeromecambon** [bonitasoft/bonita-documentation-theme#152]
One should be able to edit a page when the browser window is ~half of a (HD) screen.
A typical use case is when one have a set of syntax comments in a doc PR that she wants to fix:

<img width="1674" alt="Screenshot 2022-11-04 at 11 22 10 AM" src="https://user-images.githubusercontent.com/17833345/199950166-def410c5-122c-4154-bf7d-a73e9d324728.png">

**Comment by tbouffard** [comment]
See also discussions in https://github.com/bonitasoft/bonita-documentation-theme/pull/146#issuecomment-1294981023
